[options]

#addons_path =  /usr/lib/python2.7/dist-packages/openerp/addons,/home/ubuntu/Odoo8_Addons_boris_todo,/home/ubuntu/my_examples

# petsco   H[01)1{;w~oS|30^    Y!sP[4eTU-?]  petsco-com-au
#  service odoo restart
# monit stop   start

#service monit stop
#sudo -u odoo /home/ubuntu/new/create_load.sh
#service monit start
addons_path =  /opt/community/addons
admin_passwd = ablamtinas2015
dbfilter = odoo16
db_port = 5432
db_user = odoo
db_password = odoo

##workers = 8
##logfile = d:/odoo_log
smtp_server = 111.111.111.111 # for block SMTP
log_handler = :WARNING
#log_handler = :ERROR
#log_handler = :DEBAG
#data_dir = F:\Odoo_Attach
allow_ips = 127.0.0.1
#log_db=test_daas_04_14

#test_enable = True
