#!/bin/sh
# Create VM
# Install docker
# install pgsql:13.10 pgadmin4:7.1 odoo:16

# replace vpn-gra on <project>
# replace us-central1 on <region>
#
# !!! OPEN GCP console https://cloud.google.com/
gcloud compute firewall-rules create my-odoo-rule --allow tcp:5010,tcp:10010-10020 --source-ranges=0.0.0.0/0
gcloud compute addresses create odoo-static-ip --project=vpn-gra --network-tier=STANDARD --region=us-central1

gcloud compute instances create docker-odoo \
    --project=vpn-gra \
    --zone=us-central1-a \
    --machine-type=e2-small \
    --network-interface=address=odoo-static-ip,network-tier=STANDARD,subnet=default \
    --maintenance-policy=MIGRATE \
    --provisioning-model=STANDARD \
    --scopes=https://www.googleapis.com/auth/devstorage.read_only,https://www.googleapis.com/auth/logging.write,https://www.googleapis.com/auth/monitoring.write,https://www.googleapis.com/auth/servicecontrol,https://www.googleapis.com/auth/service.management.readonly,https://www.googleapis.com/auth/trace.append \
    --tags=http-server,https-server \
    --create-disk=auto-delete=yes,boot=yes,device-name=docker-odoo,image=projects/ubuntu-os-cloud/global/images/ubuntu-minimal-2004-focal-v20230216,mode=rw,size=10,type=projects/vpn-gra/zones/us-central1-a/diskTypes/pd-standard \
    --no-shielded-secure-boot \
    --shielded-vtpm \
    --shielded-integrity-monitoring \
    --reservation-affinity=any

# !!! wait 30 sec while starting VM
gcloud compute ssh --project=vpn-gra --zone=us-central1-a docker-odoo # start console VM

sudo apt update && sudo apt install nano && sudo apt install -y git #  Install dependencies
sudo git clone https://github.com/borisgra/docker-yaml.git --branch main
sudo chmod 777 docker-yaml/config*
cd docker-yaml/yamls
sudo bash -c "$(cat ../install_docker.sh)"
sudo docker compose up # pgsql:version+pgAdmin4:last+odoo:version  (param in .env)

# !!! wait 30 sec while starting odoo
# CLOSE GCP console