#!/bin/sh
GCP:
gcloud compute firewall-rules create my-odoo-rule --allow tcp:5010,tcp:10010-10020 --source-ranges=0.0.0.0/0
gcloud compute addresses create odoo-static-ip --project=vpn-gra --network-tier=STANDARD --region=us-central1

# create VM
gcloud compute instances create docker-odoo \
    --project=vpn-gra \
    --zone=us-central1-a \
    --machine-type=e2-small \
    --network-interface=address=odoo-static-ip,network-tier=STANDARD,subnet=default \
    --maintenance-policy=MIGRATE \
    --provisioning-model=STANDARD \
    --scopes=https://www.googleapis.com/auth/devstorage.read_only,https://www.googleapis.com/auth/logging.write,https://www.googleapis.com/auth/monitoring.write,https://www.googleapis.com/auth/servicecontrol,https://www.googleapis.com/auth/service.management.readonly,https://www.googleapis.com/auth/trace.append \
    --tags=http-server,https-server \
    --create-disk=auto-delete=yes,boot=yes,device-name=docker-odoo,image=projects/ubuntu-os-cloud/global/images/ubuntu-minimal-2004-focal-v20230216,mode=rw,size=10,type=projects/vpn-gra/zones/us-central1-a/diskTypes/pd-standard \
    --no-shielded-secure-boot \
    --shielded-vtpm \
    --shielded-integrity-monitoring \
    --reservation-affinity=any

# !!! wait 30 sec while starting VM
gcloud compute ssh --project=vpn-gra --zone=us-central1-a docker-odoo # start console VM

sudo bash -c "$(curl -fsSL https://raw.githubusercontent.com/borisgra/docker-yaml/main/install_docker.sh)"

# !!! wait 30 sec while starting odoo
# CLOSE GCP console

Adding SSHKEY VM GPS:
VM / edit  / SSH Keys / add item
ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAkf8F4vWHJ2ugTdfouGV521k4kHg+byCqQTLb/q+tIBqB2pXNAn8L7FIsE6inDGpVukUyVwVhT6UTwap1RURITRx0i/Xe+qTJt5UzjS/hL+em915TTQsT1WAuIqksbvlhx3bumvrBMoh4+0dSRdUD2yFrr3yFSiopX2D+PXKWXkHHtgmoFxUvfc2aKMbKys/fAHdJBcWkpR9jDSMEuFY+2c38TPOz9Z4AzEmnFQ0NqzQEth+GV2AVdA7UMxSSniml5RhzWplucW36iE6iS/h5fAqtGzq5d7SU0eaQMEwudbzpGlQ8J7+Fz0mkh8kFCEdpL0/PnOaJFkp+IGIrq5BEtw== google-ssh {"userName":"<name_user>","expireOn":"2025-06-01T13:57:26+0000"}

Ubuntu, Debian on Window:
sudo apt update && sudo apt install curl  # Debian on Windows
sudo apt update sudo && apt install net-tools # Ifconfig ( first ip address for inner connects and third for putty
sudo apt remove openssh-server && sudo apt install openssh-server && sudo service ssh start  # Ubuntu on Window
sudo nano /etc/ssh/sshd_config   #  ( PasswordAuthentication yes) if refuse connection - Ubuntu-20.04 on Window
sudo lsof -i -n -P | grep LISTEN # list open ports
sudo service docker start # Ubuntu/Debian if error:  Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
