FROM odoo:9.0
MAINTAINER boris.gra <boris.gra.dev@gmail.com>

USER root

RUN pip install ebaysdk
RUN pip install openpyxl==2.2.5
#ADD borisgra@github.com/mmodrive/Odoo8_Addons.git ../config_9/addons

#RUN pip install psycopg2==2.8.6 # for postgresql >= 14
#RUN pip installbs4

USER odoo

# sudo docker build -t odoo:9.0 .   # replace original image


