services:
  odoo:
    container_name: webhook
    image: webhook:latest
    build:
      context: "."
      args:
        URL_BD_CMD: ${URL_BD_COM}
    volumes:
      - .:/app
    ports:
      - "5003:5003"
    restart: always

# sudo docker compose up --build
