services:
  webhook:
    container_name: webhook
    image: webhook:latest
    build:
      context: "."
      args:
        URL_BD_CMD: ${URL_BD_COM}
    volumes:
      - .:/app
      - ./.env:/app/.env
      - ./index.html:/templates/index.html
    ports:
      - "$HOOK_PORT:$HOOK_PORT"
    restart: always

# sudo docker compose up --build
