services:
  hook:
    container_name: hook
    image: borisgra/webhook:$WEBHOOK_VERSION
    volumes:
      - ./.env:/app/.env
      - ./index.html:/templates/index.html
    ports:
      - "$HOOK_PORT:$HOOK_PORT"
    restart: always