FROM python:3.12-slim

# for cahe requirements !!!
COPY ./requirements.txt /app/requirements.txt

WORKDIR /app

RUN pip install -r requirements.txt

COPY . /app

EXPOSE 8080

ENTRYPOINT [ "python" ]

CMD ["cloudrun.py"]

# sudo docker image build  --progress=plain -t borisgra/vm:latest . 2>&1 | tee build.log
# sudo docker image build --no-cache -t borisgra/vm:latest .
# sudo docker login -u borisgra
# sudo docker push borisgra/vm:latest
# sudo docker pull borisgra/vm:latest
# sudo docker run borisgra/vm:latest -p 5004:5004
# docker builder prune  # clear cache