services:
  odooVer:
    container_name: odoo${ODOO_VERSION}
    image: odoo:${ODOO_VERSION}.0
    depends_on:
      - db
    ports:
      - "100${ODOO_VERSION}:8069"
    volumes:
      - ../config_$ODOO_VERSION:/etc/odoo
      - ../config_$ODOO_VERSION/addons:/opt/community/addons #   odoo.conf  in folder ./config_$ODOO_VERSION
      - ../config_$ODOO_VERSION:/var/lib/odoo/.local/share/Odoo
    restart: always