services:
  db:
    container_name: postgres
    image: postgres:$POSTGRES_VERSION
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PW
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ../data-$POSTGRES_VERSION:/var/lib/postgresql/data
    ports:
      - $PORTS_POSTGRES
    restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:${ADMIN4_VERSION}
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
    volumes:
      - ../config_pgadmin4:/var/lib/pgadmin
    ports:
      - "${PORTS_ADMIN4}" #"5050:80"
    restart: always

#volumes:
#  odoo-web-data:
