services:
  query:
    container_name: query
    image: borisgra/query-gra
    environment:
      - ADMIN_PASSW=+++++
      - PORT=5003
      - SERVER_TYPE=htts
      - jsr223=hide
      #      - QUERY_BD=neon-boris.gra
      - QUERY_BD=local

      #      - w=and submenu='SOUNDPROOFING'
      - DATABASE_URL_local=postgres://odoo:6Ud3RVzDQgntgcED4jUm@172.18.0.1/querys
      - DATABASE_URL_koyeb_querys=postgres://koyeb-adm:bEhm6HPl7JSF@ep-falling-shape-89504286.eu-central-1.aws.neon.tech/querys
      - DATABASE_URL_daas_nma=$NMA
      - q=v_history_today_ro
      - DATABASE_URL_neon-boris.gra=$NEON
      - DATABASE_URL_neon=$NEON
      - BIG_QUERY_vpn-gra=$VPN_GRA
    ports:
      - 5003:5003
    restart: always

  loadmenu:
    container_name: loadmenu # only JS without Python
    image: borisgra/greed:nginx-93
    environment:
      - PASS='12345'
    volumes:
      - ./menus:/usr/share/nginx/html/menus
    ports:
      - 5002:3000
    restart: always

  compurers:
    container_name: compurers
    image: borisgra/vm:ver-1.0.136
    environment:
      - PASS='12345'
    ports:
      - 5005:8080
    restart: always

#  sudo docker compose  -f compose-query.yaml --env-file .env_query up
#  sudo su -c /usr/lib/openssh/sftp-server  # for winSCP (edit/edvanset/SFTP) (debian sudo apt install openssh-server)
# RUN bash IN container loadmenu  !!
#  sudo docker compose -f compose-query.yaml --env-file .env_query exec -it -u root loadmenu  apk add bash
#  sudo docker compose -f compose-query.yaml --env-file .env_query exec -it -u root loadmenu   bash
