services:
  db:
    container_name: postgres
    image: postgres:${POSTGRES_VERSION}
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PW
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ../data-${POSTGRES_VERSION}:/var/lib/postgresql/data
    ports:
      - $PORTS_POSTGRES
    restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:${ADMIN4_VERSION}
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
    volumes:
      - ./config_pgadmin4:/var/lib/pgadmin
#      - ../config_pgadmin4:/var/lib/pgadmin
    ports:
      - "${PORTS_ADMIN4}"
    restart: always

#  sudo docker compose  -f compose-bd.yaml up
#  sudo su -c /usr/lib/openssh/sftp-server  # for winSCP (edit/edvanset/SFTP) (debian sudo apt install openssh-server)
# RUN bash IN container bd  !!
# if needed: sudo docker compose -f compose-query.yaml --env-file .env_query exec -it -u root loadmenu  apk add bash
#  sudo docker compose -f compose-query.yaml --env-file .env_query exec -it -u root loadmenu   bash
#  sudo docker compose -f compose-query.yaml --env-file .env_query exec -it loadmenu   bash  # NOT root !