services:
  odoo:
    container_name: odoo${ODOO_VERSION}
    image: odoo:${ODOO_VERSION}.0
    depends_on:
      - db
    ports:
      - "100${ODOO_VERSION}:8069"
    volumes:
      - ../config_$ODOO_VERSION:/etc/odoo
      - ../config_$ODOO_VERSION/addons:/opt/community/addons #   odoo.conf  in folder ./config_$ODOO_VERSION
      - ../config_$ODOO_VERSION:/var/lib/odoo/.local/share/Odoo
    restart: always

  db:
    container_name: postgres
    image: postgres:$POSTGRES_VERSION
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PW
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ../data-$POSTGRES_VERSION:/var/lib/postgresql/data
    ports:
      - $PORTS_POSTGRES
    restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:${ADMIN4_VERSION}
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
    volumes:
      - ../config_pgadmin4:/var/lib/pgadmin
    ports:
      - "${PORTS_ADMIN4}" #"5050:80"
    restart: always

  hook:
    container_name: hook
    image: borisgra/webhook:$WEBHOOK_VERSION
    volumes:
      - ./.env:/app/.env
      - ./myHostPipe:/app/myHostPipe
    ports:
      - "$HOOK_PORT:$HOOK_PORT"
    restart: always
