services:
  db:
    container_name: postgres
    image: postgres:$POSTGRES_VERSION
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=../data-$POSTGRES_VERSION
    volumes:
      - ../data-$POSTGRES_VERSION:/var/lib/postgresql/data-$POSTGRES_VERSION
    ports:
      - $PORTS_POSTGRES
    restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:${ADMIN4_VERSION}
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
    depends_on:
      - db
    ports:
      - "${PORTS_ADMIN4}" #"5050:80"
    restart: always

#volumes:
#  odoo-web-data:
