FROM odoo:9.0
MAINTAINER boris.gra <boris.gra.dev@gmail.com>

USER root

RUN pip install openpyxl ebaysdk
#RUN pip installbs4

USER odoo

# sudo docker build -t odoo:9.0 .   # replace original image


